apiVersion: v1
kind: Secret
metadata:
  name: apikey
type: Opaque
data:
  weather: ZGUwOWU5YWNjY21zaDIxNTNiMzhiZjRiZjVhMnAxMDQ0NmVqc24xNjQzZWFmNDhhZjE=         # de09e9acccmsh2153b38bf4bf5a2p10446ejsn1643eaf48af1
